;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        dabbrev-expand
        downcase-region
        indent-for-tab-command
        keyboard-escape-quit
        kill-region
        upcase-region
        ))

(setq mc/cmds-to-run-once
      '(
        compose-mail
        count-lines-page
        exit-recursive-edit
        flycheck-next-error
        inf-ruby
        org-self-insert-command
        org-store-link
        ))
