#!/bin/zsh
#Custom functions
_ssh() {
  echo "connecting to $1" ;
  ssh $1
}
ossh_prod() {
  _ssh "$@.$OSS_PROD_HOST" ;
}
_ossh_prod() {
  reply=(`oss_hosts $OSS_PROD_PWD builder $OSS_PROD_HOST`)
}
compctl -K _ossh_prod ossh_prod

ossh_stage() {
  _ssh "$@.$OSS_STAGE_HOST" ;
}
_ossh_stage() {
  reply=(`oss_hosts $OSS_STAGE_PWD builder $OSS_STAGE_HOST`)
}
compctl -K _ossh_stage ossh_stage
