(deftheme xoria256-kevin
  "Created 2017-04-06.")

(custom-theme-set-faces
 'xoria256-kevin
 '(highlight ((((class color) (min-colors 89)) (:foreground "black" :background "brightyellow"))))
 '(region ((((class color) (min-colors 89)) (:background "brightblue" :foreground "brightwhite"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "black" :background "color-149"))))
 '(lazy-highlight ((t (:background "brightblack" :foreground "brightwhite"))))
 '(trailing-whitespace ((((class color) (min-colors 89)) (:background "red"))))
 '(mode-line ((((class color) (min-colors 89)) (:box (:line-width -1 :style released-button) :background "color-239" :foreground "brightwhite"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:box (:line-width -1 :style released-button) :background "color-237" :foreground "color-249"))))
 '(compilation-mode-line-fail ((((class color) (min-colors 89)) (:foreground "brightred"))))
 '(compilation-mode-line-run ((((class color) (min-colors 89)) (:foreground "brightyellow"))))
 '(compilation-mode-line-exit ((((class color) (min-colors 89)) (:foreground "brightgreen"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:foreground "color-252"))))
 '(escape-glyph ((((class color) (min-colors 89)) (:foreground "color-174"))))
 '(error ((((class color) (min-colors 89)) (:foreground "brightwhite"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "color-173"))))
 '(success ((((class color) (min-colors 89)) (:foreground "color-63"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "color-110"))))
 '(font-lock-comment-face ((((class color) (min-colors 89)) (:foreground "color-244"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "color-229"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "color-182"))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:foreground "color-110"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "color-229"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "brightblue"))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "color-252"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "color-150"))))
 '(font-lock-number-face ((((class color) (min-colors 89)) (:foreground "color-180"))))
 '(hl-line ((((class color) (min-colors 89)) (:background "color-237"))))
 '(show-paren-match ((((class color) (min-colors 89)) (:foreground "brightwhite" :background "brightblue"))))
 '(default ((((class color) (min-colors 256)) (:foreground "color-252" :background "color-234")))))

(provide-theme 'xoria256-kevin)
